//! Opaque identity newtypes.
//!
//! Identities are validated strings: non-empty, at most [`ID_MAX_LEN`] bytes,
//! restricted to `[A-Za-z0-9_.:-]`. A `/` is rejected so an ID can never be
//! confused with a path segment, and control characters are rejected so an ID
//! can never smuggle log/path injection. Identities must be generated by the
//! control plane or a trusted consumer; they are never derived from Linux
//! device names, PCI BDF or backend friendly names (AGENTS rule 7, SPEC-0002
//! section 2).

use std::fmt;

use serde::{Deserialize, Serialize};

use crate::error::ApiError;

/// Maximum accepted identity length in bytes.
pub const ID_MAX_LEN: usize = 128;

fn validate(kind: &str, raw: &str) -> Result<(), ApiError> {
    if raw.is_empty() {
        return Err(ApiError::invalid_request(format!(
            "{kind} must not be empty"
        )));
    }
    if raw.len() > ID_MAX_LEN {
        return Err(ApiError::invalid_request(format!(
            "{kind} exceeds {ID_MAX_LEN} bytes"
        )));
    }
    if !raw
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'_' | b'.' | b':' | b'-'))
    {
        return Err(ApiError::invalid_request(format!(
            "{kind} contains forbidden characters (allowed: alnum, '_', '.', ':', '-')"
        )));
    }
    Ok(())
}

macro_rules! opaque_id {
    ($(#[$doc:meta])* $name:ident) => {
        $(#[$doc])*
        #[derive(
            Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize,
        )]
        #[serde(try_from = "String", into = "String")]
        pub struct $name(String);

        impl $name {
            /// Construct after validating the raw value.
            pub fn new(raw: impl Into<String>) -> Result<Self, ApiError> {
                let raw = raw.into();
                validate(stringify!($name), &raw)?;
                Ok(Self(raw))
            }

            /// Borrow the identity as a string slice.
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl TryFrom<&str> for $name {
            type Error = ApiError;
            fn try_from(value: &str) -> Result<Self, Self::Error> {
                Self::new(value)
            }
        }

        impl TryFrom<String> for $name {
            type Error = ApiError;
            fn try_from(value: String) -> Result<Self, Self::Error> {
                Self::new(value)
            }
        }

        impl From<$name> for String {
            fn from(value: $name) -> Self {
                value.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }
    };
}

opaque_id!(
    /// Opaque tenant project identity.
    ProjectId
);
opaque_id!(
    /// Opaque logical-volume identity; independent of any pool, disk, VM
    /// attachment or backend object (Volume API v2 section 9).
    VolumeId
);
opaque_id!(
    /// Opaque capacity-pool identity.
    PoolId
);
opaque_id!(
    /// Opaque physical-device identity (stable hardware identity reference,
    /// never a Linux device name or PCI BDF).
    DeviceId
);
opaque_id!(
    /// Opaque VM-attachment identity.
    AttachmentId
);
opaque_id!(
    /// Opaque host identity.
    HostId
);
opaque_id!(
    /// Opaque idempotency/operation key. Reuse with a different request
    /// payload is a conflict (Volume API v2 section 7).
    OperationId
);
opaque_id!(
    /// Opaque migration transaction identity.
    MigrationId
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_valid_ids() {
        assert!(VolumeId::new("vol-opaque").is_ok());
        assert!(ProjectId::new("tenant_42").is_ok());
        assert!(PoolId::new("pool.a:b-c").is_ok());
    }

    #[test]
    fn rejects_path_and_control_chars() {
        assert!(VolumeId::new("").is_err());
        assert!(VolumeId::new("dev/nvme0n1").is_err());
        assert!(VolumeId::new("with space").is_err());
        assert!(VolumeId::new("tab\tid").is_err());
        assert!(VolumeId::new("‽unicode").is_err());
        assert!(VolumeId::new("x".repeat(ID_MAX_LEN + 1)).is_err());
    }

    #[test]
    fn serde_round_trip() {
        let id = VolumeId::new("vol-1").expect("valid id");
        let json = serde_json::to_string(&id).expect("serialize");
        assert_eq!(json, "\"vol-1\"");
        let back: VolumeId = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, id);
    }

    #[test]
    fn serde_rejects_invalid() {
        assert!(serde_json::from_str::<VolumeId>("\"bad/id\"").is_err());
        assert!(serde_json::from_str::<VolumeId>("\"\"").is_err());
    }
}
